query orderToReturnIndividualSummary {
  productsAvailableForIndependentReturn {
    skuId
    name
    imageUrl
    currentPrice
    productId
    sellerId
    sellerName
    purchaseHistory {
      orderId
      purchaseDate
      quantityPurchased
      pricePaid
    }
  }
}