query nearestPickupPoints($lat: String!, $long: String!) {
  nearestPickupPoints(lat: $lat, long: $long)
    @context(provider: "baranda.return-app-pmi") {
    items {
      pickupPoint {
        friendlyName
        address {
          addressId
          addressType
          postalCode
          city
          state
          country
          street
          number
        }
      }
    }
  }
}
